name: aduit fix
on:
  push:
  schedule:
  - cron: "0 13 * * 1,3,5"
jobs:
  build:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        node-version: [12,14]
        
    steps:
    - uses: actions/checkout@v2
    
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: latest

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Fix packages
      run: pnpm audit fix 

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        assignees: Ovler-Young
        title: Security Update into master.
        labels: Auto PR
        branch: securityFix
