name: fetch origin
on:
  push:
  schedule:
    - cron: 0 */48 * * *   # 每隔48小时
jobs:
  fetch:
    name: fetch origin
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }} # 令牌
           upstream_repository: spencerwooo/onedrive-vercel-index  # 上游仓库
           target_repository: gchengyu/buctbase  # 你要推送的仓库
           upstream_branch: main  # 默认是拉取上游仓库的 master 分支
           target_branch: origin  # 默认推送到你的仓库 master 分支
           force: false  # 是否强制推送
           tags: true  # 确定是否使用 - tags
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v1.8.4
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: gchengyu
          issue_labels: vulnerability,test
          dedupe_issues: true
